#!/bin/bash

#SBATCH --cpus-per-task=10
#SBATCH --job-name=sock-chum_concat-mafs
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=natasha.howe@noaa.gov
#SBATCH --output=/home/nhowe/runtiming/sockeye/job_outfiles/sock-chum_concatenate-mafs_%A.out

module unload bio/angsd/0.933
module load bio/angsd/0.933

for i in /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068421.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068422.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068423.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068424.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068425.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068426.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068427.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068428.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068429.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068430.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068431.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068432.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068433.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068434.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068435.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068436.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068437.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068438.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068439.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068440.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068441.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068442.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068443.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068444.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068445.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068446.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068447.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068448.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068449.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068450.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068451.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068452.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068453.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068454.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068455.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068456.1_polymorphic.mafs.gz /home/nhowe/runtiming/sockeye/gls/sock-chum_NC_068457.1_polymorphic.mafs.gz
do zcat $i | tail -n +2 -q >> /home/nhowe/runtiming/sockeye/gls/sock-chum_wholegenome_polymorphic.mafs; done
cut -f 1,2,3,4 /home/nhowe/runtiming/sockeye/gls/sock-chum_wholegenome_polymorphic.mafs > /home/nhowe/runtiming/sockeye/gls/sock-chum_wholegenome_polymorphic.sites
gzip /home/nhowe/runtiming/sockeye/gls/sock-chum_wholegenome_polymorphic.mafs

angsd sites index /home/nhowe/runtiming/sockeye/gls/sock-chum_wholegenome_polymorphic.sites
